#!/usr/bin/env bash

###############################################################################
# DeepScholar-Bench: End-to-End Pipeline Runner
#
# This script runs the core DeepScholar-Bench pipeline on fixed input/output locations.
#
# It performs:
#   1. Research synthesis report generation by DeepScholar-Base (deepscholar_base)
#   2. Automated evaluation of results using the holistic eval suite (eval)
#
# USAGE:
#   ./scripts/run_all.sh
#
# REQUIREMENTS:
#   - Python 3.10+
#   - All dependencies from requirements.txt installed (ideally in a new conda env)
#   - The following dataset files generated by data_pipeline:
#       ./dataset/queries.csv
#       ./dataset/papers_with_related_works.csv
#       ./dataset/important_citations.csv
#       ./dataset/gt_nuggets_outputs/  (directory; required for eval)
#   - Config files:
#       configs/deepscholar_base.yaml
#       configs/eval.yaml
#
# To create the dataset directory and files, run the data collection pipeline:
#   python -m data_pipeline.main --categories cs.AI --start-date 2025-05-01
#
# OUTPUTS:
#   - Generation results:   ./outputs/results/
#   - Evaluation results:   ./outputs/evaluation/
#
# By default, evaluation is performed after report generation.
# To skip evaluation, set SKIP_EVAL=true at the start of the script.
###############################################################################

set -e

DATASET_DIR="./dataset"
RESULTS_DIR="./outputs/results"
EVAL_DIR="./outputs/evaluation"

DEEPSCHOLAR_CONFIG="configs/deepscholar_base.yaml"
EVAL_CONFIG="configs/eval.yaml"
SKIP_EVAL=false  # Set to true to skip evaluation

if [[ ! -d "$DATASET_DIR" ]]; then
  echo "ERROR: Dataset directory does not exist: $DATASET_DIR"
  echo "       Please generate it using the data pipeline before running this script."
  echo "       e.g., python -m data_pipeline.main --categories cs.AI --start-date 2025-05-01"
  exit 1
fi
if [[ ! -f "$DATASET_DIR/queries.csv" ]]; then
  echo "ERROR: $DATASET_DIR/queries.csv not found."
  exit 1
fi
if [[ ! -f "$DATASET_DIR/papers_with_related_works.csv" ]]; then
  echo "ERROR: $DATASET_DIR/papers_with_related_works.csv not found."
  exit 1
fi
if [[ ! -f "$DATASET_DIR/important_citations.csv" ]]; then
  echo "ERROR: $DATASET_DIR/important_citations.csv not found."
  exit 1
fi
if [[ ! -d "$DATASET_DIR/gt_nuggets_outputs" ]]; then
  echo "ERROR: $DATASET_DIR/gt_nuggets_outputs directory not found."
  exit 1
fi

mkdir -p "$RESULTS_DIR"
mkdir -p "$EVAL_DIR"

# Step 1: Research Synthesis (DeepScholar-Base)
python -m deepscholar_base.main \
    --queries-file "$DATASET_DIR/queries.csv" \
    --output-folder "$RESULTS_DIR" \
    --config-yaml "$DEEPSCHOLAR_CONFIG"

# Step 2: Automated Evaluation
if [ "$SKIP_EVAL" = false ]; then
  python -m eval.main \
    --modes deepscholar_base \
    --evals all \
    --input-folder "$RESULTS_DIR" \
    --output-folder "$EVAL_DIR" \
    --dataset-path "$DATASET_DIR/papers_with_related_works.csv" \
    --important-citations-path "$DATASET_DIR/important_citations.csv" \
    --nugget-groundtruth-dir-path "$DATASET_DIR/gt_nuggets_outputs" \
    --config-yaml "$EVAL_CONFIG"

  echo
  echo "Evaluation completed successfully."
  echo
else
  echo "Skipping evaluation step as requested (SKIP_EVAL=true)."
  echo
fi

# Summary report
echo "=========================================="
echo "Pipeline Complete!"
echo "=========================================="
echo
echo "Generated Artifacts:"
[ "$SCRAPE_NEW_DATA" = true ] && echo "  Dataset:     $DATASET_DIR/"
echo "  Results:     $RESULTS_DIR/"
[ "$SKIP_EVAL" = false ] && echo "  Evaluation:  $EVAL_DIR/"
echo
echo "=========================================="